

CREATE TABLE `wp_commentmeta` (
  `meta_id` bigint(20) unsigned NOT NULL,
  `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");
INSERT INTO wp_commentmeta VALUES("","","","");



CREATE TABLE `wp_comments` (
  `comment_ID` bigint(20) unsigned NOT NULL,
  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT '0',
  `comment_author` tinytext NOT NULL,
  `comment_author_email` varchar(100) NOT NULL DEFAULT '',
  `comment_author_url` varchar(200) NOT NULL DEFAULT '',
  `comment_author_IP` varchar(100) NOT NULL DEFAULT '',
  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` text NOT NULL,
  `comment_karma` int(11) NOT NULL DEFAULT '0',
  `comment_approved` varchar(20) NOT NULL DEFAULT '1',
  `comment_agent` varchar(255) NOT NULL DEFAULT '',
  `comment_type` varchar(20) NOT NULL DEFAULT '',
  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO wp_comments VALUES("","","","","","","","","","","","","","","");
INSERT INTO wp_comments VALUES("","","","","","","","","","","","","","","");
INSERT INTO wp_comments VALUES("","","","","","","","","","","","","","","");
INSERT INTO wp_comments VALUES("","","","","","","","","","","","","","","");
INSERT INTO wp_comments VALUES("","","","","","","","","","","","","","","");
INSERT INTO wp_comments VALUES("","","","","","","","","","","","","","","");



CREATE TABLE `wp_inceptio_fonts` (
  `id` int(6) NOT NULL,
  `font_name` varchar(128) NOT NULL,
  `font_url` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `wp_links` (
  `link_id` bigint(20) unsigned NOT NULL,
  `link_url` varchar(255) NOT NULL DEFAULT '',
  `link_name` varchar(255) NOT NULL DEFAULT '',
  `link_image` varchar(255) NOT NULL DEFAULT '',
  `link_target` varchar(25) NOT NULL DEFAULT '',
  `link_description` varchar(255) NOT NULL DEFAULT '',
  `link_visible` varchar(20) NOT NULL DEFAULT 'Y',
  `link_owner` bigint(20) unsigned NOT NULL DEFAULT '1',
  `link_rating` int(11) NOT NULL DEFAULT '0',
  `link_updated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `link_rel` varchar(255) NOT NULL DEFAULT '',
  `link_notes` mediumtext NOT NULL,
  `link_rss` varchar(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




CREATE TABLE `wp_options` (
  `option_id` bigint(20) unsigned NOT NULL,
  `option_name` varchar(64) NOT NULL DEFAULT '',
  `option_value` longtext NOT NULL,
  `autoload` varchar(20) NOT NULL DEFAULT 'yes'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");
INSERT INTO wp_options VALUES("","","","");

